version: "3.8"

networks:
  git_network:

x-check-ports: &check-ports ./bin/check-ports:/bin/check-ports
x-service-template: &template
  restart: on-failure
  networks:
    - git_network
  healthcheck: &hc
    interval: 5s
    timeout: 3s
    start_period: 10s
    retries: 10
  volumes:
    - *check-ports

services:
  manager:
    image: neshkeev/bash-notebook
    hostname: &name manager
    container_name: *name
    healthcheck:
      <<: *hc
      test: bash /bin/check-ports 8888
    ports:
      - "8888:8888"
    volumes:
      - *check-ports
      - ./work:/home/jovyan/work
    environment:
      USER_NAME: Nikita Eshkeev
      USER_EMAIL: neshkeev@yandex.ru
      NOTEBOOK_ARGS: --NotebookApp.token='' --NotebookApp.password=''
      RESTARTABLE: yes
